// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJHCMog_0lyajPamNJh8ufXpbyGKUjscI',
    appId: '1:521307839291:web:81caf2e3804881984e751e',
    messagingSenderId: '521307839291',
    projectId: 'aceeby2022',
    authDomain: 'aceeby2022.firebaseapp.com',
    storageBucket: 'aceeby2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfw8abpQGTBw0q7xv23eqhwT5R-rotj20',
    appId: '1:521307839291:android:61d1d3936888c6a44e751e',
    messagingSenderId: '521307839291',
    projectId: 'aceeby2022',
    storageBucket: 'aceeby2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaiRa0UEK12IjwFHvg-LGD4iV2aKQ_pLs',
    appId: '1:521307839291:ios:508ce3c29013e9b24e751e',
    messagingSenderId: '521307839291',
    projectId: 'aceeby2022',
    storageBucket: 'aceeby2022.appspot.com',
    iosClientId: '521307839291-34h3o9ohun3kuokl435u7cbe6lrqe39t.apps.googleusercontent.com',
    iosBundleId: 'com.mastermindsarl.aceebyGala2022',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaiRa0UEK12IjwFHvg-LGD4iV2aKQ_pLs',
    appId: '1:521307839291:ios:c8fed6754707bf254e751e',
    messagingSenderId: '521307839291',
    projectId: 'aceeby2022',
    storageBucket: 'aceeby2022.appspot.com',
    iosClientId: '521307839291-h2nbvf1kafoc18s38spus6393npql011.apps.googleusercontent.com',
    iosBundleId: 'com.example.aceebyGala2022',
  );
}
